name: xx01 - Building Blocks

# on: workflow_dispatch

on: pull_request

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful Step
        run:  |
          echo "I will Succeed"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye, World!"
