name: 03 - Workflow Runners

on: push


jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on an Ubuntu runner."
          echo "Runner OS: $RUNNER_OS"
      #  $RUNNER_OS is not a standard Linux environment variable. It is a special environment variable set by GitHub Actions runners
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a Windows runner."
          echo "Runner OS: $RUNNER_OS"