name: 16 - Working with Environments
run-name: 16 - Working with Environments - env ${{ inputs.target-env }}

on:
  workflow_dispatch:
    # inputs:
    #   target-env:
    #     type: environment
    #     default: staging

jobs:
  echo-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my-env-value }}"
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my-env-value }}"
        
  